name: senbrua
version: "1.0.0"
title: Senbrua
summary: A simple, modern sound recorder for GNOME
license: GPL-3.0-or-later
contact: https://github.com/otabekoff/senbrua
website: https://github.com/otabekoff/senbrua
source-code: https://github.com/otabekoff/senbrua
issues: https://github.com/otabekoff/senbrua/issues
description: |
  Senbrua is a modern remake of Vocalis - a simple and elegant sound recorder
  application for the GNOME desktop. It allows you to record audio using your
  microphone and play it back with a beautiful waveform visualization.

  Features:
  - Record audio in multiple formats (Opus, Vorbis, FLAC, MP3)
  - Playback recordings with interactive waveform visualization
  - RNNoise-powered noise reduction (toggleable)
  - Rename recordings for easy organization
  - Export recordings to your preferred location
  - Dark mode support with libadwaita
  - Responsive design - works on desktop and mobile

  Based on Vocalis (https://gitlab.gnome.org/World/vocalis)

grade: stable
confinement: strict
base: core22
compression: lzo

slots:
  senbrua:
    interface: dbus
    bus: session
    name: uz.mohirlab.senbrua

apps:
  senbrua:
    command: usr/local/bin/senbrua
    plugs:
      - audio-record
      - audio-playback
      - home
      - removable-media
      - desktop
      - gsettings
    desktop: usr/local/share/applications/uz.mohirlab.senbrua.desktop
    common-id: uz.mohirlab.senbrua
    environment:
      GTK_USE_PORTALS: "1"

layout:
  /usr/share/glib-2.0/schemas:
    bind: $SNAP/usr/share/glib-2.0/schemas

parts:
  meson-deps:
    plugin: nil
    override-build: |
      pip3 install meson
      craftctl default
    build-packages:
      - python3-pip
    override-prime: ""

  senbrua:
    after: [meson-deps]
    plugin: meson
    source: .
    meson-parameters:
      - --prefix=/usr/local
      - -Dskip_ts=true
    build-packages:
      - ninja-build
      - gettext
      - libgjs-dev
      - libgtk-4-dev
      - libadwaita-1-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - gobject-introspection
      - gir1.2-gstreamer-1.0
      - gir1.2-gst-plugins-base-1.0
      - gir1.2-gst-plugins-bad-1.0
      - gir1.2-adw-1
      - gir1.2-gtk-4.0
    stage-packages:
      - gjs
      - libgtk-4-1
      - libadwaita-1-0
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer-plugins-good1.0-0
      - libgstreamer-plugins-bad1.0-0
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-pulseaudio
      - gir1.2-gstreamer-1.0
      - gir1.2-gst-plugins-base-1.0
      - gir1.2-gtk-4.0
      - gir1.2-adw-1
      - libpulse0
      - dconf-gsettings-backend
    organize:
      usr/local/share/uz.mohirlab.senbrua: usr/share/uz.mohirlab.senbrua
      usr/local/share/icons: usr/share/icons
      usr/local/share/applications: usr/share/applications
      usr/local/share/glib-2.0: usr/share/glib-2.0
      usr/local/bin/senbrua: usr/local/bin/senbrua
